### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by salimbenfarhat** [satansdeer/react-firebase-auth#2]
`Module not found: Can't resolve 'firebase/app' in 'C:\Users\Utilisateur\Documents\react\learning-center-react\src'
`
How to resolve it please?

**Comment by junipdewan** [comment]
@salimbenfarhat  I have solved this issue by upgrading the firebase version to latest & adding new API key value. You can have this [PR](https://github.com/satansdeer/react-firebase-auth/pull/9) as a reference

**Comment by satansdeer** [comment]
Thanks @junipdewan, your PR is merged now
